[buildPlans.liosevka]
family = "Liosevka"
spacing = "term"
serifs = "sans"
no-cv-ss = false

  [buildPlans.liosevka.variants]
  inherits = "ss12"

    [buildPlans.liosevka.variants.design]
    capital-a = "curly-serifless"
    capital-c = "serifless"
    capital-d = "standard-serifless"
    capital-g = "toothless-corner-inward-serifed-hooked"
    capital-h = "serifless"
    capital-i = "serifed"
    capital-k = "curly-serifless"
    capital-p = "closed"
    capital-q = "straight"
    capital-r = "curly"
    capital-s = "serifless"
    capital-v = "curly"
    capital-w = "curly"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    a = "double-storey-serifless"
    b = "toothed"
    d = "toothed-serifless"
    g = "double-storey"
    k = "curly-serifless"
    m = "short-leg"
    n = "straight"
    p = "eared"
    r = "serifless"
    u = "toothed"
    v = "curly"
    w = "curly"
    x = "curly-serifless"
    y = "curly"
    lower-lambda = "curly"
    lower-xi = "rounded"
    cyrl-capital-ka = "curly-serifless"
    cyrl-ka = "curly-serifless"
    cyrl-capital-u = "curly"
    cyrl-capital-ya = "curly"
    cyrl-ya = "curly"
    zero = "slashed"
    one = "no-base"
    two = "straight-neck"
    four = "closed-non-crossing"
    five = "vertical-upper-left-bar"
    six = "straight-bar"
    seven = "straight-serifed"
    eight = "crossing"
    nine = "straight-bar"
    asterisk = "penta-low"
    pilcrow = "high"
    caret = "high"
    number-sign = "upright-tall"
    ampersand = "upper-open"
    at = "threefold-tall"
    percent = "dots"
    bar = "natural-slope"
    lig-ltgteq = "slanted"
    diacritic-dot = "round"

  [buildPlans.liosevka.ligations]
  inherits = "clike"
